version: '3.7'

services:
  agendavoluntaria-ui:
    image: unisociesc/agendavoluntaria-ui:#{tag}#
    networks:
      - frontend
      - backend
    deploy:
      replicas: 10
      update_config:
        delay: 15s
        parallelism: 5
        failure_action: rollback
      rollback_config:
        parallelism: 5
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.agendavoluntaria-ui.rule=Host(`triagemcovid19.prodcom.com.br`)"
        - "traefik.http.routers.agendavoluntaria-uiagendavoluntaria-ui.entrypoints=websecure"
        - "traefik.http.routers.agendavoluntaria-ui.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.agendavoluntaria-ui.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
  backend:
    external: true
